### PR TITLE
Updating `polynomial` module

### PR DESCRIPTION
**Pull request by Autoparallel**
# Description

Added a bunch of documentation for the `polynomial` modules.  Also removed an unnecessary `PhantomData`.

### CODE REVIEW

**Comment by laudiacay** [comment]
are you concerned you'll have to do a second pass? this module is incomplete and will eventually have more functions, i think

**Comment by Autoparallel** [comment]
> are you concerned you'll have to do a second pass? this module is incomplete and will eventually have more functions, i think

No I'm okay with it. I can iterate on things here. This was a good learning xp and I feel more confident in how these things fit together. 

In general I'm good with multiple passes -- I like iterative development!

**Comment by laudiacay** [comment]
if you rebase i can merge?

**Comment by 0xJepsen** [comment]
@Autoparallel want to vibe on this over the weekend?

**Comment by laudiacay** [comment]
hey @Autoparallel did this somehow make it in somewhere to main? I'm trying to merge and I'm finding a lot of "the exact same changes x2"...

**Comment by laudiacay** [comment]
lmk if not. i'm going to hold off on finishing the merge for now

**Comment by Autoparallel** [comment]
@laudiacay @0xJepsen I'm just going to scrap this. Not really important anyway.

**Pull request closed without merging**
