### PR TITLE
move to arkworks grumpkin and use curve config

### PR DESCRIPTION
**Pull request by lonerapier**
# Description

include changes to move grumpkin to arkworks curve and using `SWCurveConfig` trait.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Refactor (non-breaking change that updates existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Comments have been added/updated

Please delete options that are not relevant.

### CODE REVIEW

**Comment by laudiacay** [comment]
going to make some tiny changes

**Review by laudiacay — APPROVED** [review]
looks good to me, i just completed some tiny nits to get the tests running (in the future please check that the tests run!)

**Comment by laudiacay** [comment]
also please let me know if you're waiting on my review! sorry I let this sit so long.

**Comment by lonerapier** [comment]
thanks. super sorry for not checking tests.
will keep in mind for the future.

**Pull request merged**
